### ISSUE TITLE
how do i add a stub link

### ISSUE THREAD

**Issue by Ilovecatsmiau123** [FLUORESCENTXX/Image-logger-roblox#1]

**Comment by Ilovecatsmiau123** [comment]
please dm me how to do this on discord $ Cats 8692

**Comment by FLUORESCENTXX** [comment]
its in the stub link

**Comment by Ilovecatsmiau123** [comment]
> e stub link

how ? whats that bro jst dm me and screenshare explaining it then we wilk be cool

**Comment by Ilovecatsmiau123** [comment]
Can u do the tutorial right i did use lunar stub builder like u said but how do i attach it to the index.tml explain more better ples

**Comment by FLUORESCENTXX** [comment]
Your meant to put the stub in the stub link area. Just download the html and edit it and upload it to your site. Explained it mostly in the readme. Can you not read?

**Comment by Ilovecatsmiau123** [comment]
> 

Ight thank you finally a better explanation jeez
